### ISSUE TITLE
卡在競選人的背影的loading畫面過不去

### ISSUE THREAD

**Issue by Brli** [audreyt/democracy3-taiwan-mod#1]
不能玩？

**Comment by audreyt** [comment]
請問 D3 的版本號（Steam or non-Steam），以及有開哪些 DLC？

**Comment by Brli** [comment]
1.20
看來是安裝的方式出問題：
README.md 上說是安裝到遊戲資料夾
但是遊戲本身的「資料夾」卻是有個mods，裡面放他能安裝的mod
所以我以為是要把壓縮檔放到那邊
實際上是把git repo放在根目錄

2017-12-10 10:23 GMT+08:00 唐鳳 <notifications@github.com>:
